{
  enterprise(id: "RW50ZXJwcmlzZU5vZGU6MQ==") {
    couriers {
      edges {
        node {
          id
          email
          isAvailable
          contact {
            edges {
              node {
                names
                lastnames
              }
            }
          }
        }
      }
    }
  }
}
