{
  allOrders{
    edges{
      node{
        client{
          id
        }
        id
        date,
        estimatedTime,
        location,
        details{
          edges{
            node{
              quantity,
              product{
                id,
                name,
                price,
                enterprise{
                  name
                  
                },
              }
            }
          }
        }
      }
    }
  }
}