{
    allOrders {
    edges{
      node{
        id,
        status,
        location
        products{
          edges{
            node{
              name
              price
              enterprise{
                id
              }
            }
          }
        }
      }
    }
  }
}