query allNotifications($id: ID!) {
  user(id: $id) {
    notifications {
      edges {
        node {
          id
          title
          message
          read
          created
        }
      }
    }
  }
}
