{
  allOrders(status: "despachado") {
    edges {
      node {
        id
        status
        location
        date
        client{
          email
        }
        details {
          edges {
            node {
              quantity
              product {
                name
                price
                enterprise {
                  id,
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
