{
  allOrders{
    edges{
      node{
        client{
          id,
          email
        }
        id
        date,
        estimatedTime,
        location,
        status
        details{
          edges{
            node{
              quantity,
              product{
                id,
                name,
                price,
                preparation
                estimatedTime
                enterprise{
                  name,
                  location
                  
                },
              }
            }
          }
        }
      }
    }
  }
}




