{
  allOrders(status: "nuevo") {
    edges {
      node {
        id
        status
        location
        details {
          edges {
            node {
              quantity
              product {
                name
                price
                enterprise {
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
