mutation createEnterprise($name: String!, $location: String!,$businessHours: String!) {
  createEnterprise(input: { name: $name, location: $location, businessHours: $businessHours }) {
    enterprise {
      id
      name
      location
      businessHours
    }
  }
}

