mutation createEnterprise($name: String!, $location: String!,$businessHours: String!,$historical_review: String!) {
  createEnterprise(input: { name: $name, location: $location, businessHours: $businessHours, historical_review : $historical_review }) {
    enterprise {
      id
      name
      location
      businessHours
      historical_review
    }
  }
}

