mutation updateEnterprise($id: ID!, $name: String, $location: String, $businessHours: String) {
  updateEnterprise(input: { id: $id, name: $name, location: $location, businessHours: $businessHours }) {
    enterprise {
      id
      name
      location
      businessHours
    }
  }
}
