query enterprise($id: ID!) {
  enterprise(id: $id) {
    name
    products {
      edges {
        node {
          orders {
            edges {
              node {
                id
                status
                client {
                  id
                  email
                }
                review {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
