query enterprise($id: ID!) {
  enterprise(id: $id)  {
    name
      products{
        edges{
          node{
            orders{
              edges{
                node{
                  client{
                    email
                  }
                  review{
                    comments
                    qualityService
                    presentation
                    preparation
                    ingredients
                    price
                    textures
                    cookingPoint
                  }
                }
              }
            }
          }
        }
      }
    }
  }
