query userByEmail($email: String!){
  allUsers(email: $email) {
    edges {
      node {
        contact {
          edges {
            node {
              names
              lastnames
              location
              telephone
            }
          }
        }
      }
    }
  }
}
