query usersEnterprise($email: String) {
  allManagers(email: $email) {
    edges {
      node {
        id
        email
        enterprises {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    }
  }
}