{
  allProducts {
    edges {
      node {
        id
        productType
        name
        price
        ingredients
        preparation
        estimatedTime
        active
        accompaniments {
          edges {
            node {            
              id
              name
              productType
              price
              ingredients
              preparation
              active
            }
          }
        }
        enterprise {
          id
        }
        images {
          edges {
            node {
              id
              url
            }
          }
        }
      }
    }
  }
}
