{
	allDeliveries{
    edges {
      node {
        deliveryTime
        id
        courier{
          id
          email
          
        }
        order{
          
          id
          status
        details {
          edges {
            node {
              product {
                name
                price
                enterprise {
                  name
                }
              }
              quantity
            }
          }
        }
      }
    }
  }
}
}