
{
  allOrders {
    edges {
      node {
        id
        estimatedTime
        status
            details {
          edges {
            node {
              quantity
              product {
                name
                price
                enterprise {
                  name
                }
                
              }
            }
          }
        }
        client {
          id
          email
        }
        courier {
          id
          email
        }
    
        
      }
    }
  }
}