query manager($id: ID!){
 	manager(id: $id){
        enterprises{
          	edges{
            	node{
                id
                name
                location
                businessHours
                created
                status
                historicalReview
              }
            }
          }
  }
}
