{
  allEnterprises {
    edges {
      node {
        id
        name
        city
        location
        businessHours
        created
        status
        historicalReview
        image
      }
    }
  }
}
