mutation createPedido(
  $estimatedTime: String!
  $location: String!
  $clientId: ID!
) {
  createOrder(
    input: {
      estimatedTime: $estimatedTime
      location: $location
      clientId: $clientId
    }
  ) {
    order {
      id
      location
      estimatedTime
    }
  }
}
